### ISSUE TITLE
Создать всплывающее окно проигрыша

### ISSUE THREAD

**Issue by nikitakaralyus** [nikitakaralyus/MarkOneCyber#18]
- [x] https://drive.google.com/file/d/1XqBWax29QzQhoMxO78w38YhOXLRA7qnA/view?usp=sharing - Скачайте схему окна проигрыша
- [x] Не копируйте цвета со схемы, они используются только для обозначения элементов в ней

Обратите внимание, что
- [x] Синий - картинка (UI-Image в Unity)
- [x] Серый - текст (Text Mesh Pro в Unity)
- [x] Зеленый - кнопка (Button TMP в Unity)
- [x] Желтый - панель (UI - Panel в Unity)
- [x] Не копируйте схему точь в точь, текстом на схеме обозначено, что это за элемент. В местах где должен быт текст (серый блок) поставьте 0000, на кнопках текст должен быть только там, где отмечен красным цветом

После этого
- [x] Создайте свою ветку от main
- [x] Опубликуйте свою ветку
- [x] Выберите сцену UI
- [x] Создайте на ней Canvas и назовите его Respawn pop-up window
- [x] Опираясь на схему, добавьте туда необходимые элементы
- [x] Убедитесь, что добавили все элементы и добавили правильно
- [x] Запушьте изменения в ветку и сообщите о выполнении

**Comment by phuljkeee** [comment]
I take it
